title: KsirBlog
SEOTitle: ksirBlog
header-img: img/home-bg.jpg
future: true
permalink: pretty
paginate: 6
# exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          
plugins: [jekyll-paginate]
markdown: kramdown
kramdown:
  input: GFM                           
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
sidebar: true                           # whether or not using Sidebar.
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value
friends: [
    {
      title: "æŠ–éŸ³å»æ°´å°",
      href: "https://3g.gljlw.com/diy/douyin.php"
    },{
      title: "æ°¸é¡ºeç›˜",
      href: "http://sj.ysupan.com/zjkgf"
    },{
        title: "æŠ–éŸ³",
        href: "https://www.iesdouyin.com/share/user/MS4wLjABAAAATE8xICluCm9y1DSER2FUkbKWP_uWXFsXjwQ803MuAHthXwGKplJrkI1Vz1E4pcSn?u_code=1e054ag2mcgb&did=MS4wLjABAAAAU2I8iJAMjMS-An2PwSb1MDRxd3iQu-PdnpZK8l4Y6Xw&iid=MS4wLjABAAAAUi-gJnMx37uA5fY_6Z3hN4930RdNSujuIGAU2FxDy2Q&with_sec_did=1&sec_uid=MS4wLjABAAAATE8xICluCm9y1DSER2FUkbKWP_uWXFsXjwQ803MuAHthXwGKplJrkI1Vz1E4pcSn&from_ssr=1&from_aid=2329&life_share_ext=%7B%22life_share_id%22:%22181eafa0373e4ae6ae812ddd890cbf9f%22,%22from_user_id%22:1533187673307667%7D&utm_campaign=client_share&app=douyin_lite&utm_medium=ios&tt_from=copy&utm_source=copy"
    },{
        title: "Youtubeæ‹›å•†",
        href: "https://m.youtube.com/@YsCfzy/shorts"
    },{
        title: "ä¸‹è½½ğŸ¶",
        href: "https://www.xiazaitool.com"
    },{
        title: "ä¸“ä¸šé˜²æ°´æŠ€æœ¯",
        href: "https://rsxj.github.1io/"
    },{
        title: "GitHub",
        href: "https://www.github.com/"
    },{
        title: "189é‚®ç®±",
        href: "https://open.e.189.cn/api/logbox/separate/wap/login.html?appId=189mail&clientType=20100&format=redirect&version=v1.1&paras=1F5EEF7CD0B5492A47A1AE5BE7ABF233E9029B6280FFC099ECAD928AE8D867AB378C38D2AE0CC63B4270BD9B7D23CB1B2C016AF80426828482BBD00D099A49808D2EFA025E56DFBD29E39FD3CCE12CA7410100514AB1F32ECC32A9C5D7E815CDFCE81E18B3CB3FF6130272F860A729AC6F3A841C8DFB4ABC299D8DC4E02DA9A31622031429816A56659D3C0D4F9DA95688A07FC65DD3B0EAED036E641D28E6684EEE1BCDF65708A214FCF9B65FF602DDFFD1F16CB830A6AEB877120E9B07ECB069DA82CE9E3261EBF81A384079DA339BA2CE687EA5261E56A6603AF05EA45E81BB338C26&sign=2EFBBEC889F0C9C684282E810BFC3E5F3DDDE7F1&protocol=https&netType="
    },{
        title: "google mail",
        href: "https://mail.google.com"
    },{
        title: "gitå†™åš",
        href: "https://github.com/Stjkzzy/Stjkzzy.github.io/tree/master/_posts"
    } ,{
        title: "æ¢å±±ç«‹é¸¿äºŒæ‰‹è®¾å¤‡ä¹°å–",
        href: ""
    } ,{
        title: "æˆ‘çš„ç²¾çµ",
        href: ""
    },{
        
        title: "è‰æ–™ç½‘",
        href: "https://cli.im/tools"
    } ,{
    title: "é¦–é¡µ",
        href: "https://Stjkzzy.github.io"
    } ,{
        title: "å›¾ç‰‡å‹ç¼©",
        href: "https://yasuo.xunjiepdf.com/img/"
    } ,{
        title: "å›é¦–é¡µ",
        href: "https://bcjk.us.kg"
    } 
]    



            
theme: jekyll-theme-cayman
